version: "3"
services:
  risk-calculator-app: 
    container_name: risk-calculator-container
    image: risk-calculator-app
    restart: always
    build: .
    ports:
      - 9090:9090
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      
  mysqldb:
    container_name: riskcalculatorsqldb
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: dynamic
      MYSQL_ROOT_PASSWORD: root